version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - USERNAME=myuser
      - PASSWORD=mypassword
      - HOST=postgres
      - DATABASE=mydatabase
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: myuser    
      POSTGRES_PASSWORD: mypassword  
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - app_network

volumes:
  pgdata:
    driver: local

networks:
  app_network:
    driver: bridge