version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: myuser    
      POSTGRES_PASSWORD: mypassword  
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
    driver: local
