// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
)

type RefreshToken struct {
	TokenID   int32
	UserID    string
	Token     string
	ExpiresAt int32
}

type User struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
	Username string
}
